# Generated by Django 3.1.5 on 2021-01-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDeatils',
            new_name='UserDetail',
        ),
    ]
